computer_move_listener:
  ros__parameters:
    home: [0.0, 0.0, 0.0, 0.0]

    cell_0: [0.24435, 0.38397, -0.41888, 1.45]   # 14, 22, -24 완료
    cell_1: [0.00000, 0.35, -0.41888, 1.47]   # 0, 22, -24 완료
    cell_2: [-0.24435, 0.38397, -0.41888, 1.45]  # -14, 22, -24 완료
    cell_3: [0.31416, 0.08727, -0.16, 1.50353]    # 18, 0, 0, 
    cell_4: [0.00000, 0.00000, 0.00000, 1.4]    # 0, 0, 0, 
    cell_5: [-0.31416, 0.00000, 0.00000, 1.4]   # -18, 0, 0, 
    cell_6: [0.40143, -0.24435, 0.26180, 1.4]   # 23, -14, 15, 
    cell_7: [0.00000, -0.41888, 0.38397, 1.4]   # 0, -24, 22, 
    cell_8: [-0.40143, -0.24435, 0.26180, 1.4]  # -23, -14, 15, 

    loading_zone: [3.14159, -0.69813, 0.52360, 1.6] # 180, -40, 30,