computer_move_listener:
  ros__parameters:
    home: [0.0, 0.0, 0.0, 0.0]

    cell_0: [0.24435, 0.38397, -0.41888, 1.57080]   # 14, 22, -24, 90
    cell_1: [0.00000, 0.38397, -0.41888, 1.57080]   # 0, 22, -24, 90
    cell_2: [-0.24435, 0.38397, -0.41888, 1.57080]  # -14, 22, -24, 90
    cell_3: [0.31416, 0.00000, 0.00000, 1.57080]    # 18, 0, 0, 90
    cell_4: [0.00000, 0.00000, 0.00000, 1.57080]    # 0, 0, 0, 90
    cell_5: [-0.31416, 0.00000, 0.00000, 1.57080]   # -18, 0, 0, 90
    cell_6: [0.40143, -0.24435, 0.26180, 1.57080]   # 23, -14, 15, 90
    cell_7: [0.00000, -0.41888, 0.38397, 1.57080]   # 0, -24, 22, 90
    cell_8: [-0.40143, -0.24435, 0.26180, 1.57080]  # -23, -14, 15, 90

    loading_zone: [3.14159265, -0.78539816, 0.52359878, 1.57079633]