computer_move_listener:
  ros__parameters:
    home: [0.0, 0.0, 0.0, 0.0]
    loading_zone: [3.0, 0.0, 0.0, 0.0]

    cell_0: [1.0, 0.0, 0.0, 0.0]
    cell_1: [1.2, 0.0, 0.0, 0.0]
    cell_2: [1.4, 0.0, 0.0, 0.0]
    cell_3: [1.6, 0.0, 0.0, 0.0]
    cell_4: [1.8, 0.0, 0.0, 0.0]
    cell_5: [2.0, 0.0, 0.0, 0.0]
    cell_6: [2.2, 0.0, 0.0, 0.0]
    cell_7: [2.4, 0.0, 0.0, 0.0]
    cell_8: [2.6, 0.0, 0.0, 0.0]
