computer_move_listener:
  ros__parameters:
    home: [0.0, 0.0, 0.0, 0.0]

    cell_0: [0.225, 0.38397, -0.41888, 1.45]   # 완료
    cell_1: [0.00000, 0.35, -0.41888, 1.47]   # 완료
    cell_2: [-0.225, 0.38397, -0.41888, 1.45]  # 완료
    cell_3: [0.29, 0.12, -0.11, 1.45]    # 완료
    cell_4: [0.00000, -0.05, 0.1, 1.32]    # 완료
    cell_5: [-0.29, 0.12, -0.11, 1.45]   # 완료 
    cell_6: [0.38, -0.24435, 0.26180, 1.43]   # 완료 
    cell_7: [0.00000, -0.37, 0.34, 1.4]   # 완료 
    cell_8: [-0.38, -0.24435, 0.26180, 1.43]  # 완료 

    loading_zone: [3.14159, -0.69813, 0.52360, 1.6] # 완료