computer_move_listener:
  ros__parameters:
    # 1. 홈 포지션 (선택 사항)
    home: [0.0, 0.0, 0.0, 0.0]

    # 2. 틱택토 0~8번 칸의 각도 (joint_names 개수인 4개와 맞춰야 함)
    cell_0: [1.0, 0.0, 0.0, 0.0]
    cell_1: [2.0, 0.0, 0.0, 0.0]
    cell_2: [3.0, 0.0, 0.0, 0.0]
    cell_3: [4.0, 0.0, 0.0, 0.0]
    cell_4: [5.0, 0.0, 0.0, 0.0]
    cell_5: [6.0, 0.0, 0.0, 0.0]
    cell_6: [7.0, 0.0, 0.0, 0.0]
    cell_7: [8.0, 0.0, 0.0, 0.0]
    cell_8: [9.0, 0.0, 0.0, 0.0]
